ruby/config/routes.rb
Rails.application.routes.draw do
  resources :papers do
    member do
      get :read
      get :save
      get :star
      get :download
    end
  end
  

  root 'welcome#index'

end

ruby/app/models/paper.rb
class Paper < ActiveRecord::Base

  require 'nokogiri'
  include HTTParty
  debug_output $stdout
  #database = "pubmed"

  @search_url  = 'http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi'
  @fetch_url   = 'http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi'
  @doi_url     = 'http://dx.doi.org'

  # Params for destructuring Pubmed XML Response
  @base_xpath     = '//PubmedArticleSet/PubmedArticle/MedlineCitation/Article'
  @journal_xpath  = @base_xpath + '/Journal'
  @title_xpath    = @base_xpath + '/ArticleTitle'
  @abstract_xpath = @base_xpath + '/Abstract/AbstractText'
  @doi_xpath      = @base_xpath + '/ELocationID'
  
  # author information is deeply nested and must be interated over (it's a list)
  @author_base  = @base_xpath + '/AuthorList/Author'
  @author_lname = @author_base + '/LastName'
  @author_fname = @author_base + '/ForeName'
  @author_intls = @author_base + '/Initials'
  @author_aff   = @author_base + '/AffiliationInfo/Affiliation'
  
  # Can I do this? Will Ruby let me do this??? IDK...
  # Having the xpaths in a lookup table of sorts would be much easier and save memory
  #@xpaths = {
  #  base: '//PubmedArticleSet/PubmedArticle/MedlineCitation/Article',
  #  journal: @xpaths['base'] + '/Journal',
  #  title: @xpaths['base'] + '/ArticleTitle',
  #  abstract: @xpaths['base'] + '/Abstract/AbstractText',
  #  author: {
  #    base: @xpaths['base'] + '/AuthorList/Author',
  #    lname: @xpaths['author']['base'] + '/LastName',
  #    fname: @xpaths['author']['base'] + '/ForeName',
  #    initials: @xpaths['author']['base'] + '/Initials',
  #    affiliation: @xpaths['author']['base'] + '/AffiliationInfo/Affiliation'
  #  }
  #}

  @default_options = {
    query: {
      db: 'pubmed',
      retmode: 'xml'
    }
  }
  
  def self.search_remote(term="")

    @papers = {}
    
    options = {query: @default_options[:query].merge({term: term})}
    puts options
    
    r = get('http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi', options)
    

    # An array of paper IDs from the search result
    pids = r["eSearchResult"]["IdList"]["Id"]
    puts pids

    pids.each do |pid|
      # get the titles and abstracts of each id
      params = @default_options[:query].merge({id: pid})
      s = get(@fetch_url, params)
      puts s.body
      @papers[pid] = {
        title: Nokogiri::XML(s.body).at_xpath(@title_xpath).content,
        abstract: Nokogiri::XML(s.body).at_xpath(@abstract_xpath).content,
        link: @doi_url + Nokogiri::XML(s.body).at_xpath(@doi_xpath).content
      }
    end
  end


  def self.read_remote(doc_id)

    params = default_options.merge({query: {id: doc_id }})

    r = get(@fetch_url, params)
    
  end


  def download!
    # 
  end
  
  def self.default_options
    {
      query: {
        db: 'pubmed',
        retmode: 'xml'
      }
    }
  end
  
end

ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby/app/controllers/papers_controller.rb
class PapersController < ApplicationController
  def read
    @paper = Paper.find(params[:id])
  end

  def save
  end

  def star
  end

  def download
  end
end

ruby/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/app/helpers/paper_helper.rb
module PaperHelper
end

ruby/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daily Scholar</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="#">Daily Scholar</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<ul class="nav navbar-nav">
          <li><a href="/latest">Latest</a></li>
	  <li><a href="/mine">Recommended For You</a></li>
	</ul>
	<form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search Articles">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
	</form>
	<ul class="nav navbar-nav navbar-right">
	  <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Your Profile <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Customizations</a></li>
              <li><a href="#">Saved Articles</a></li>
            </ul>
          </li>
	</ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
	
  <div class="container"><%= yield %></div>

  <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

ruby/app/views/papers/download.html.erb
<h1>Paper#download</h1>
<p>Find me in app/views/paper/download.html.erb</p>

ruby/app/views/papers/read.html.erb
<h2><%= @paper.title %></h2>
<section class="paper-body"><%= @paper.body %></section>

ruby/app/views/papers/save.html.erb
<h1>Paper#save</h1>
<p>Find me in app/views/paper/save.html.erb</p>

ruby/app/views/papers/star.html.erb
<h1>Paper#star</h1>
<p>Find me in app/views/paper/star.html.erb</p>

ruby/app/views/welcome/index.html.erb
<h1>Welcome to Daily Scholar</h1>
<p>Placeholder</p>
<%= link_to "Read Paper", read_paper_path(Paper.last) %>